### ISSUE TITLE
Website Acceptance 

### ISSUE THREAD

**Issue by galorosero** [Mountainman97/WebDocuments19-20#5]
We leave you the link for the main site of Picture world for you to accept it or if you have a request please let us know.

 Main site:

https://astrojebus.github.io/PictureWorlds/

**Comment by BadrAlzein** [comment]
Good lets see if u can make it better. 
1-we have an issue with the red bar. u can do much better on the color and the design + the search TF in that bar don't go anywhere-. 
2- when i go to the about Page lets say. the nav will indicates that i am in the home cuz the home btn in the navbar is always have the white line. 
3. find a non error Page by pressing the send Btn in the contact us. 
4. Social media Btns will go only to the home (better if u done it for the home of the Sites like FB.com)
5. in the responsive site u have the nav that takes almost 90% from the mobile screen (fix that!) the colors of tha nav in the mobile and ipads are just red on blue.. i guess u can make it better.   
<img width="1146" alt="Bildschirmfoto 2020-01-21 um 10 52 33" src="https://user-images.githubusercontent.com/57675922/72794339-25512280-3c3c-11ea-99bc-208da23ff976.png">
